#!/bin/sh
# npm run build
npm run build
rsync -av ./ u97170284@217.160.196.7:~/SYMFONY --include=public/build --include=public/.htaccess --exclude-from=.gitignore --exclude=".*"
ssh u97170284@217.160.196.7 'cd ~/SYMFONY && php7.3-cli bin/console cache:clear'